baseurl = "localhost:1313"
languageCode = "en-us"
title = "HyperLogLog playground"
theme = "simple"
publishDir = "docs"

[permalinks]
    post = ":section/:year/:month/:day/:title/"

[params]
	title = "HyperLogLog playground"
	subtitle = ""
	copyright = "Released under the MIT license."
	pageNotFoundTitle = "404 - Page not found"
