name = "Steam"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "A minimal theme for bloggers."
homepage = "//github.com/digitalcraftsman/hugo-steam-theme"
tags = ["google analytics", "disqus", "blog", "minimal"]
features = []
min_version = 0.20

